Repository itz-arnav/JIRA-TICKET-MANAGEMENT-SYSTEM, pull requests merged in 2022-10, with the labels that each got.

#16 updated stylesheet
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#15 update style.css
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#17 updated readme, style.css
  README.md
  script.js
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#18 changing bg color
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#21 Added hover effect, rounded edges
  script.js
  style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#23 added favicon
  favicon.ico
  index.html
  site.webmanifest
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#25 Updated Stylesheet
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#27 Udated style CSS
  style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#30 Create index1.html
  index1.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#29 changes style
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#31 Color change #7
  .vscode/settings.json
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#32 Formatted buttons
  style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#34 changes done -Changing some colors in index.html #33
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing

#37 Done some changes in index1.html #36
  index1.html
  stylee.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, amazing
